version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      SECRET_KEY_BASE: your_secret_key_here
