default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: bsm_development

test:
  <<: *default
  database: bsm_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
